{% set version = "0.2.34" %}

package:
  name: xvfbwrapper
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/x/xvfbwrapper/xvfbwrapper-{{ version }}.tar.gz
  sha256: e7f195f30f0ab4e39c5a66e19e0d0bfee0ce5afb3f49e0ae4e5a491a8417db2a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - xvfbwrapper

about:
  home: https://github.com/cgoldberg/xvfbwrapper
  license: MIT
  license_file: LICENSE
  summary: 'run headless display inside X virtual framebuffer (Xvfb)'

extra:
  recipe-maintainers:
    - satra
    - ryanvolz
