{% set version = "0.2.21" %}

package:
  name: xvfbwrapper
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xvfbwrapper/xvfbwrapper-{{ version }}.tar.gz
  sha256: bad4c7a0d60feea5f8c7cb0c58bc20dfb48225ca50207e4d9e80360e88b1ecc9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - xvfbwrapper

about:
  home: https://github.com/cgoldberg/xvfbwrapper
  license: MIT
  license_file: LICENSE
  summary: 'run headless display inside X virtual framebuffer (Xvfb)'

extra:
  recipe-maintainers:
    - satra
    - ryanvolz
