{% set version = "0.2.9" %}

package:
  name: xvfbwrapper
  version: {{ version }}

source:
  fn: xvfbwrapper-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/x/xvfbwrapper/xvfbwrapper-{{ version }}.tar.gz
  md5: 3f3cbed698606f4b14e76ccc7b5dd366

build:
  number: 1002
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]    

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - xvfbwrapper

about:
  home: https://github.com/cgoldberg/xvfbwrapper
  license: MIT
  license_file: LICENSE
  summary: 'run headless display inside X virtual framebuffer (Xvfb)'

extra:
  recipe-maintainers:
    - satra
