{% set version = "0.2.35" %}

package:
  name: xvfbwrapper
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/x/xvfbwrapper/xvfbwrapper-{{ version }}.tar.gz
  sha256: a4e1a6fcce157357b287495f8e3a7e4379eae656fad166692b0181459f926fad

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - xvfbwrapper

about:
  home: https://github.com/cgoldberg/xvfbwrapper
  license: MIT
  license_file: LICENSE
  summary: 'run headless display inside X virtual framebuffer (Xvfb)'

extra:
  recipe-maintainers:
    - satra
    - ryanvolz
