{% set version = "0.2.10" %}

package:
  name: xvfbwrapper
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xvfbwrapper/xvfbwrapper-{{ version }}.tar.gz
  sha256: d662cf8f266efd3d0a1c022eebb8d2c04083d6e87fd81392fb5400d95036ed8c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - xvfbwrapper

about:
  home: https://github.com/cgoldberg/xvfbwrapper
  license: MIT
  license_file: LICENSE
  summary: 'run headless display inside X virtual framebuffer (Xvfb)'

extra:
  recipe-maintainers:
    - satra
    - ryanvolz
