{% set version = "0.2.14" %}

package:
  name: xvfbwrapper
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xvfbwrapper/xvfbwrapper-{{ version }}.tar.gz
  sha256: f6e42ae827e308c211f60db3c9301be6d6849701f2de1060954c9dc53d9ebf6b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - xvfbwrapper

about:
  home: https://github.com/cgoldberg/xvfbwrapper
  license: MIT
  license_file: LICENSE
  summary: 'run headless display inside X virtual framebuffer (Xvfb)'

extra:
  recipe-maintainers:
    - satra
    - ryanvolz
