appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: osUwV+pOnDP+G6VXXhpg++9lFJFtj4awKDW/ZPiAb9gOWY4OI71w07N9u+pOlqkntas9W5Rmbdmi4wGTYVA79U7KVu3sHP5OtBkMErjIR86WsdulbLkPdWjjTHb1S6iQFSFe3g7VJaJ+F1JyJkfpCoUkeGanoePQVd7qxC/maJeGsRagx5iK2zK7yMij0IO4tCPLBDPgubGtIQ8kqJjvRDjIdhdU0xWQr1DM2vFF3co5nkhl65x/qXKTIggcK7HsWa8d4WCEOJuUq7zutbcZvAPRen6DoTIIkVQt6ChEmZ7/RUjnezjkAYRebEkD0SrlsfBhJU2aOq2th0LMY21gEeocwFsx9AQQ8bgjXnVnfB7rBMW9IwD/nCBVHyIhRnes/lDc7qWUFRxLyZ+W7CCd4ZH2FDHiL5x6PimD0449fPZrjWm3AEn17K0Fj5TcsEdOR2rOLX2Rw0fLbkjla/lW8uwnUslF4iSn35f2+GevFFsExBDx+w+o6uo1hIiWmB+r9jebolSutw2P/G4x/JVP0UTB8zqiZyv+1uzbp6pIuwSTE0d/3PAZwzVnMhXGfsZmOY3Y5QMRpo6oNZfHbt3J1LRF8t9G+0iHzl9SafbxMIMaTXmxJR1dt0TST8YHq8pPUNJhDKKO/56RlkJp7AbfQuHlYfMPp1SZE2kjpGIkD1g=}
